CREATE TABLE `a1402978`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `comment` TEXT(500) NULL,
  PRIMARY KEY (`id`));
